import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { readlink } from "fs";
import styled from "styled-components";
const Main = styled.main`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;
const FormWrapper = styled.div`
  margin-top: 50px;
  margin-bottom: 50px;
`;
const Card = styled.div`
  // border: 1px solid black;
  // background-color: grey;
  border-radius: 5px;
  box-shadow: rgba(50, 50, 93, 0.25) 0px 6px 12px -2px,
    rgba(0, 0, 0, 0.3) 0px 3px 7px -3px;
  width: 400px;
  margin-bottom: 20px;
`;
const CardHeader = styled.div`
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  padding: 20px 0;
  font-size: 1.5em;
  font-weight: bold;
`;
const CardBodyItem = styled.div`
  padding-top: 5px;

  padding-bottom: 5px;
`;
const CardBody = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding-bottom: 30px;
`;
interface IBans {
  last_banReason: string;
}
interface IRank {
  rankScore: number;
  rankName: string;
  rankDiv: number;
  rankImg: string;
}
interface IPlayer {
  name: string;
  level: number;
  arena: object;
  rank: IRank;
  platform: string;
  battlepass: object;
  bans: IBans;
}

const Home: NextPage = () => {
  const [search, setSearch] = useState<string>("");
  const [platform, setPlatform] = useState<string>("PC");
  const [results, setResults] = useState<any>([]);
  const handleInput = (e: any) => {
    // console.log(e.target.value);
    setSearch(e.target.value);
  };
  const handlePlatform = (e: any) => {
    setPlatform(e.target.value);
  };
  const handleSubmit = (e: any) => {
    e.preventDefault();
    fetch(
      `https://api.mozambiquehe.re/bridge?auth=${process.env.NEXT_PUBLIC_API_KEY}&player=${search}&platform=${platform}`
    )
      .then((response) => response.json())
      .then((data) => {
        if (data.global) {
          console.log(data.global.level);
          console.log(data.global.name);
          setResults((old: any) => [...old, data.global]);
        }
      })
      .catch((err) => console.log(err));
  };
  useEffect(() => {
    console.log(results);
  }, [results]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <FormWrapper>
          <form onSubmit={handleSubmit}>
            <select
              name="platform"
              id="platform=-select"
              onChange={handlePlatform}
            >
              <option value="PC">Platform</option>
              <option value="PC">PC</option>
              <option value="PS4">PS4</option>
              <option value="X1">XBOX</option>
            </select>
            <input
              type="text"
              placeholder="Search for Player"
              onChange={handleInput}
            ></input>
            <input type="submit" value={"+"}></input>
          </form>
        </FormWrapper>
        {/* <div>{test && test.username}</div> */}
        <div>
          {results.map((obj: IPlayer, index: number) => {
            return (
              <Card key={obj.name}>
                <CardHeader>
                  <img src={obj.rank.rankImg} width={50}></img>
                  <span>{obj.name}</span>
                </CardHeader>
                <CardBody>
                  <CardBodyItem>
                    Level: {obj.level > 500 ? 500 : obj.level}
                  </CardBodyItem>
                  <CardBodyItem>Points: {obj.rank.rankScore}</CardBodyItem>
                  {/* <CardBodyItem>
                    Last Ban:
                    {obj.bans.last_banReason == "COMPETITIVE_DODGE_COOLDOWN" &&
                      "Dodged Game"}
                  </CardBodyItem> */}
                </CardBody>
                {/* <div>Remove</div> */}
              </Card>
            );
          })}
        </div>
      </Main>
      {/* 
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Footer Here
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
